### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by ar2rsawseen**

### CODE REVIEW

**Comment by ronkorving** [comment]
@ar2rsawseen Just mentioning this in case you're not aware, but you can test against more than one version of Node at once:

```yaml
language: node_js
node_js:
  - "10"
  - "8"
```

Assuming you still officially support 8... which you may not, I don't know :)

**Comment by ar2rsawseen** [comment]
We upgrade nodejs version together with Countly, so current release needs to support only specific nodejs version it will run on :)

**Comment by ronkorving** [comment]
@ar2rsawseen Ah, so we're on 10 now? :) Cool

**Comment by ar2rsawseen** [comment]
Yea, I hope so :)

**Pull request merged**
