### PR TITLE
[frontend] Fix delete data when u of platformVersion is zero

### PR DESCRIPTION
**Pull request by vagromghost**

### CODE REVIEW

**Comment by ar2rsawseen** [comment]
Hello,
as far as I know that is exactly what compact is supposed to do:
http://underscorejs.org/#compact

Do you have any specific problems or use cases when this does not work?

**Comment by vagromghost** [comment]
Hi, I'm having a problem. For example :
image

**Comment by ar2rsawseen** [comment]
Sorry, firstly
What is active users?
Secondly, how does the fix you provide help with that?

**Comment by vagromghost** [comment]
active users is num of 'u' .
image
Fix the problem which can't draw the horizontal stacked bars of platform versions.
at "#/analytics/platforms" 
image

**Comment by ar2rsawseen** [comment]
I see, so what confused me that there is Total users for me and not Active users, so I wondered if it was some kind of modification or not :)
image

But ok, my main point was that compact should do exactly the same thing you are doing, by its definition. So at least from code changes I don't see how it would differ.

Can you provide the input data, the one that you receive from /o?method=device_details so I can try use it and reproduce, to understand why compact method does not behave like it should for you.

**Comment by vagromghost** [comment]
I don't change anything, except the name . "ACTIVE USERS" is "TOTAL USERS" . 
`_.compact`  can remove all falsy including `0` .  
the input data is to long . I only provide problem related data in mongodb .  

> The selected time period is from 2018-01-01 to 2018-01-02.
> The data about the device named `a4:5` at 2018-01-01.
> image
> And The data about the device named tom at 2018-01-02 is none.
> `u` of  the device named `a4:5` is zero under the above conditions.
> The reason for the above phenomenon is that when the number of new users (`n`) is less than total users (`u`), the new number of users ( `n`) is assigned to total users (`u`).
image

**Comment by ar2rsawseen** [comment]
The code you highlighted shows if n is larger than u, not less, then u = n because total users per period cannot be less than new users. And the result for the data should be u = 1 and n = 0, so it should not reset u = n in this case. I think problem you experience is somewhere else, but unfortunately without data I cannot reproduce it.

And I still fail to see how your fix can help with the problem
```
platformVersionTotal = _.without(platformVersionTotal, false, null, "", undefined, NaN);
```

**Comment by vagromghost** [comment]
Sorry. I take a error. 
> The selected time period is from 2018-01-01 to 2018-01-02.
> The data about the device named `a4:5` at 2018-01-01.
> image
> And The data about the device named `a4:5` at 2018-01-02 is none.
> The number of total users (`u` ) of the device named `a4:5` calculated by the method `countlyCommon.extractTwoLevelData` under the above conditions is zero
> The reason for the above phenomenon is that tmpUniqVal of `a4:5` is greater than tmpUniqValCheck of `a4:5`, the tmpPropertyObj["u"] is assigned to zero.
> image
debug code is 
`
            for (var j = 0; j < rangeArray.length; j++) {

                var propertySum = 0,
                    tmpPropertyObj = {},
                    tmp_x = {};

                for (var i = periodMin; i < periodMax; i++) {
                    dataObj = countlyCommon.getDescendantProp(db, countlyCommon.periodObj.currentPeriodArr[i] + "." + rangeArray[j]);
                    if (rangeArray[j] == 'a4:5') {
                        console.log(JSON.stringify(dataObj) + "-----------1");
                    }
                    if (!dataObj) {
                        continue;
                    }

                    dataObj = clearFunction(dataObj);

                    for (var k = 0; k < propertyNames.length; k++) {

                        if (propertyNames[k] == "u") {
                            propertyValue = 0;
                        } else if (propertyFunctions[k]) {
                            propertyValue = propertyFunctions[k](rangeArray[j], dataObj);
                        } else {
                            propertyValue = dataObj[propertyNames[k]];
                        }

                        if (!tmpPropertyObj[propertyNames[k]]) {
                            tmpPropertyObj[propertyNames[k]] = 0;
                        }

                        if (typeof propertyValue === 'string') {
                            tmpPropertyObj[propertyNames[k]] = propertyValue;
                        } else {
                            propertySum += propertyValue;
                            tmpPropertyObj[propertyNames[k]] += propertyValue;
                        }
                    }
                    if (rangeArray[j] == 'a4:5') {
                        console.log(JSON.stringify(tmpPropertyObj) + "-----------2");
                    }
                }

                if (propertyNames.indexOf("u") !== -1 && Object.keys(tmpPropertyObj).length) {
                    if (countlyTotalUsers.isUsable() && estOverrideMetric && calculatedObj[rangeArray[j]]) {

                        tmpPropertyObj["u"] = calculatedObj[rangeArray[j]];
                        if (rangeArray[j] == 'a4:5') {
                            console.log(JSON.stringify(tmpPropertyObj) + "-----------3");
                        }

                    } else {
                        var tmpUniqVal = 0,
                            tmpUniqValCheck = 0,
                            tmpCheckVal = 0;

                        for (var l = 0; l < (countlyCommon.periodObj.uniquePeriodArr.length); l++) {
                            tmp_x = countlyCommon.getDescendantProp(db, countlyCommon.periodObj.uniquePeriodArr[l] + "." + rangeArray[j]);
                            if (!tmp_x) {
                                continue;
                            }
                            tmp_x = clearFunction(tmp_x);
                            propertyValue = tmp_x["u"];

                            if (typeof propertyValue === 'string') {
                                tmpPropertyObj["u"] = propertyValue;
                            } else {
                                propertySum += propertyValue;
                                tmpUniqVal += propertyValue;
                                tmpPropertyObj["u"] += propertyValue;
                            }
                        }
                        if (rangeArray[j] == 'a4:5') {
                            console.log(JSON.stringify(tmpPropertyObj) + "-----------4");
                        }

                        for (var l = 0; l < (countlyCommon.periodObj.uniquePeriodCheckArr.length); l++) {
                            tmp_x = countlyCommon.getDescendantProp(db, countlyCommon.periodObj.uniquePeriodCheckArr[l] + "." + rangeArray[j]);
                            if (!tmp_x) {
                                continue;
                            }
                            tmp_x = clearFunction(tmp_x);
                            tmpCheckVal = tmp_x["u"];

                            if (typeof tmpCheckVal !== 'string') {
                                propertySum += tmpCheckVal;
                                tmpUniqValCheck += tmpCheckVal;
                            }
                        }
                        if (rangeArray[j] == 'a4:5') {
                            console.log(JSON.stringify(tmpPropertyObj) + "-----------5");
                        }
                        if (tmpUniqVal > tmpUniqValCheck) {
                            if (rangeArray[j] == 'a4:5') {
                                console.log(tmpUniqVal+ "------"+ tmpUniqVal +  "---------" + tmpUniqValCheck + "-----------1");
                            }
 
                            tmpPropertyObj["u"] = tmpUniqValCheck;
                        }
                        if (rangeArray[j] == 'a4:5') {
                            console.log(JSON.stringify(tmpPropertyObj) + "-----------6");
                        }
                    }

                    // Total users can't be less than new users
                    if (tmpPropertyObj.u < tmpPropertyObj.n) {
                        tmpPropertyObj.u = tmpPropertyObj.n;
                    }
                    if (rangeArray[j] == 'a4:5') {
                        console.log(JSON.stringify(tmpPropertyObj) + "-----------7");
                    }

                    // Total users can't be more than total sessions
                    if (tmpPropertyObj.u > tmpPropertyObj.t) {
                        tmpPropertyObj.u = tmpPropertyObj.t;
                    }
                    if (rangeArray[j] == 'a4:5') {
                        console.log(JSON.stringify(tmpPropertyObj) + "-----------8");
                    }
                }
                if (rangeArray[j] == 'a4:5') {
                    console.log(JSON.stringify(tmpPropertyObj) + "-----------9");
                }
                tableData[tableCounter] = {};
                tableData[tableCounter] = tmpPropertyObj;
                tableCounter++;
            }
`
output is 
`
{"u":1,"t":2,"n":0}-----------1 debugger eval code:10:25
{"os_version":"a4:5","t":2,"u":0,"n":0}-----------2 debugger eval code:40:25
undefined-----------1 debugger eval code:10:25
{"os_version":"a4:5","t":2,"u":1,"n":0}-----------4 debugger eval code:74:29
{"os_version":"a4:5","t":2,"u":1,"n":0}-----------5 debugger eval code:91:29
1------1---------0-----------1 debugger eval code:95:33
{"os_version":"a4:5","t":2,"u":0,"n":0}-----------6 debugger eval code:101:29
{"os_version":"a4:5","t":2,"u":0,"n":0}-----------7 debugger eval code:110:25
{"os_version":"a4:5","t":2,"u":0,"n":0}-----------8 debugger eval code:118:25
{"os_version":"a4:5","t":2,"u":0,"n":0}-----------9
`

**Comment by ar2rsawseen** [comment]
Ok, thank you I will recheck it, but if its true, your fix would not fix it, as you only replace `_.compact` with `_.without` am I right?

**Comment by vagromghost** [comment]
Sorry , My english is so bad .
image
I don't know why tmpUniqVal  assigned to tmpUniqValCheck. so I just fix the problem which can't draw the horizontal stacked bars of platform versions.

**Pull request merged**
