### PR TITLE
Configure Docker via environment variables

### PR DESCRIPTION
**Pull request by cihangir**
Current docker is not configurable. When someone wants to configure api, dashboard or nginx, needs to do a custom build for countly.

### CODE REVIEW

**Comment by iartem** [comment]
That's... one of not so many really great pull requests here! 👍

**Comment by cihangir** [comment]
Hey guys i think this PR is ready to review, please check and let me know.

package.json only has "traverse" as addition, but "npm i --save" orders the packages accordingly hence that many change. If you'd like i can revert that.

As per the tests, it seems they are flaky, i have no idea if the failures are caused by my changes. In case of flakiness could you please rebuild the PR?

**Comment by ar2rsawseen** [comment]
Restarted build, all check passed. It seems we are good to go, if @iartem does not have any objections :)

**Comment by cihangir** [comment]
rebased and resolved the conflict in package.json. PTAL.

**Comment by ar2rsawseen** [comment]
Hello, just FYI, we are waiting to release patch versions 16.12.3 (hopefully this week) and after that we can merge your PR and test it more thoroughly.

**Pull request merged**
