### PR TITLE
[SER-1548] [Deepscan] Token-manager. Loop with splice should be rewriten to preven out of bounds error

### PR DESCRIPTION
**Pull request by YavuzYilmazz**

### CODE REVIEW

**Review by coskunaydinoglu — COMMENTED** [review]
@YavuzYilmazz Wouldn't it cause infinite loop since you are decrementing j while it is incremented in for loop?

**Comment by YavuzYilmazz** [comment]
> @YavuzYilmazz Wouldn't it cause infinite loop since you are decrementing j while it is incremented in for loop?

@coskunaydinoglu I think this wouldn't be the problem here. In fact, the suggestion was to add break, but I thought it wouldn't work because the array size would also change. But I can add break if you think there is a problem

**Comment by coskunaydinoglu** [comment]
In fact this j-- does not have any affect since it is already looped. @YavuzYilmazz I think this is false positive. Array length is already checked. With j-- or without it works correctly

**Comment by YavuzYilmazz** [comment]
> In fact this j-- does not have any affect since it is already looped. @YavuzYilmazz I think this is false positive. Array length is already checked. With j-- or without it works correctly

Yes that's true, it could be a false positive situation. Let me try to check this, I need to look at examples.

**Review by cihadtekin — APPROVED** [review]
better to use `array.prototype.filter` next time

**Pull request merged**
