### PR TITLE
Ingress file for baremetal/unmanaged k8 setup

### PR DESCRIPTION
**Pull request by ihaardik**
Ingress file for baremetal and unmanaged k8 setup

### CODE REVIEW

**Review by kaanklky — APPROVED** [review]

**Comment by kaanklky** [comment]
I'm waiting for discussion on JIRA task before merging this PR.

**Comment by ar2rsawseen** [comment]
Fixes https://github.com/Countly/countly-server/issues/3362 and https://github.com/Countly/countly-server/issues/3440

**Comment by nahsi** [comment]
> Fixes #3362 and #3440

Is should help with #3362 but #3440 doesn't seem like an issue with routing.

**Comment by ar2rsawseen** [comment]
True, removed it, thank you :)

**Pull request merged**
