### PR TITLE
fix: no more hardcoded IS_FLEX flag.

### PR DESCRIPTION
**Pull request by frknbasaran**

### CODE REVIEW

**Review by ar2rsawseen — APPROVED** [review]

**Comment by can-keklik** [comment]
LGTM

**Comment by ArtursKadikis** [comment]
> LGTM

based take

**Comment by can-keklik** [comment]
You don't ever leave that chair K, do you?

**Comment by ArtursKadikis** [comment]
> You don't ever leave that chair K, do you?

image

**Comment by can-keklik** [comment]
kudos for the enthusiasm...

**Pull request merged**
